# Site settings
title: Allen security notes
email: none
description: >-
  Share some knowledge, skills and others — security research, pentesting notes and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username: allencharp
author: allencharp

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
